### ISSUE TITLE
Do you have these SWF files still? 

### ISSUE THREAD

**Issue by z0mbieslayer** [magical/pdw#1]
Not really an issue, but I didn’t know where to put it. I was wondering if you still have these, since it’s no longer possible to obtain them.

**Comment by z0mbieslayer** [comment]
I'm still wondering if you have them. A user by the name of shutterbug2000 was looking for them not long ago because he wants to bring back the service. Any response from you at this point would be greatly appreciated!

**Comment by magical** [comment]
Here's the snapshot I gave shutterbug. It's my pdw directory when i was working on this repo. All the swf files i have are in there (mostly pokemon graphics, but also a few of the main swfs).

https://turnipmints.mooo.com/~andrew/tmp/pdw-snapshot-2014.7z
